steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['clean','install']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-south1-docker.pkg.dev/deploy-cicd-java/javastarted/get-java-started', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-south1-docker.pkg.dev/deploy-cicd-java/javastarted/get-java-started']
    timeout: 500s
  # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=kubernetes/deployment.yaml
    - --image=us-south1-docker.pkg.dev/deploy-cicd-java/javastarted/get-java-started
    - --location=us-central1
    - --cluster=java-started