# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: started-java
  labels:
    app: started-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: started-java
  template:
    metadata:
      labels:
        app: started-java
    spec:
      containers:
      - name: started-java-get
        image: us-south1-docker.pkg.dev/ci-cd-nmp/javastarted/get-java-started
        ports:
        - containerPort: 9080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "get-started-service"
  namespace: "default"
  labels:
    app: "started-java"
spec:
  ports:
    - port: 80
      protocol: "TCP"
      targetPort: 9080
  selector:
    app: "started-java"
  type: "LoadBalancer"
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'
spec:
  type: NodePort
  selector:
    app: metrics
    department: sales
  ports:
  - name: my-https-port
    port: 443
    targetPort: 8443
  - name: my-http-port
    port: 80
    targetPort: 50001
